[toolchain]
package_manager = "yarn"
anchor_version = "0.30.1"

[features]
resolution = true
skip-lint = false

[programs.localnet]
stake_test = "F1JH85HfWhojoEyTPq5jJHqjoEt1hPaSR9QthvCvLs9r"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
